# Generated by CMake 3.5.1

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget aws-cpp-sdk-core aws-cpp-sdk-access-management aws-cpp-sdk-autoscaling aws-cpp-sdk-acm aws-cpp-sdk-apigateway aws-cpp-sdk-cloudhsm aws-cpp-sdk-cloudformation aws-cpp-sdk-cloudfront aws-cpp-sdk-cloudsearch aws-cpp-sdk-cloudsearchdomain aws-cpp-sdk-cloudtrail aws-cpp-sdk-codecommit aws-cpp-sdk-codedeploy aws-cpp-sdk-codepipeline aws-cpp-sdk-cognito-identity aws-cpp-sdk-cognito-sync aws-cpp-sdk-config aws-cpp-sdk-datapipeline aws-cpp-sdk-devicefarm aws-cpp-sdk-directconnect aws-cpp-sdk-dms aws-cpp-sdk-ds aws-cpp-sdk-dynamodb aws-cpp-sdk-ec2 aws-cpp-sdk-ecs aws-cpp-sdk-ecr aws-cpp-sdk-elasticache aws-cpp-sdk-elasticbeanstalk aws-cpp-sdk-elasticfilesystem aws-cpp-sdk-elasticloadbalancing aws-cpp-sdk-elasticmapreduce aws-cpp-sdk-elastictranscoder aws-cpp-sdk-email aws-cpp-sdk-es aws-cpp-sdk-events aws-cpp-sdk-firehose aws-cpp-sdk-gamelift aws-cpp-sdk-glacier aws-cpp-sdk-iam aws-cpp-sdk-importexport aws-cpp-sdk-inspector aws-cpp-sdk-iot aws-cpp-sdk-identity-management aws-cpp-sdk-kinesis aws-cpp-sdk-kms aws-cpp-sdk-lambda aws-cpp-sdk-logs aws-cpp-sdk-machinelearning aws-cpp-sdk-marketplacecommerceanalytics aws-cpp-sdk-mobileanalytics aws-cpp-sdk-meteringmarketplace aws-cpp-sdk-monitoring aws-cpp-sdk-opsworks aws-cpp-sdk-queues aws-cpp-sdk-rds aws-cpp-sdk-redshift aws-cpp-sdk-route53 aws-cpp-sdk-route53domains aws-cpp-sdk-s3 aws-cpp-sdk-sdb aws-cpp-sdk-sns aws-cpp-sdk-sqs aws-cpp-sdk-ssm aws-cpp-sdk-storagegateway aws-cpp-sdk-sts aws-cpp-sdk-support aws-cpp-sdk-swf aws-cpp-sdk-transfer aws-cpp-sdk-waf aws-cpp-sdk-workspaces)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target aws-cpp-sdk-core
add_library(aws-cpp-sdk-core SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-core PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "JSON_USE_EXCEPTION=0;AWS_CUSTOM_MEMORY_MANAGEMENT"
  INTERFACE_COMPILE_OPTIONS "-std=c++11"
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-core/include"
)

# Create imported target aws-cpp-sdk-access-management
add_library(aws-cpp-sdk-access-management SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-access-management PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-access-management/include"
)

# Create imported target aws-cpp-sdk-autoscaling
add_library(aws-cpp-sdk-autoscaling SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-autoscaling PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-autoscaling/include"
)

# Create imported target aws-cpp-sdk-acm
add_library(aws-cpp-sdk-acm SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-acm PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-acm/include"
)

# Create imported target aws-cpp-sdk-apigateway
add_library(aws-cpp-sdk-apigateway SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-apigateway PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-apigateway/include"
)

# Create imported target aws-cpp-sdk-cloudhsm
add_library(aws-cpp-sdk-cloudhsm SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-cloudhsm PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-cloudhsm/include"
)

# Create imported target aws-cpp-sdk-cloudformation
add_library(aws-cpp-sdk-cloudformation SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-cloudformation PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-cloudformation/include"
)

# Create imported target aws-cpp-sdk-cloudfront
add_library(aws-cpp-sdk-cloudfront SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-cloudfront PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-cloudfront/include"
)

# Create imported target aws-cpp-sdk-cloudsearch
add_library(aws-cpp-sdk-cloudsearch SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-cloudsearch PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-cloudsearch/include"
)

# Create imported target aws-cpp-sdk-cloudsearchdomain
add_library(aws-cpp-sdk-cloudsearchdomain SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-cloudsearchdomain PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-cloudsearchdomain/include"
)

# Create imported target aws-cpp-sdk-cloudtrail
add_library(aws-cpp-sdk-cloudtrail SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-cloudtrail PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-cloudtrail/include"
)

# Create imported target aws-cpp-sdk-codecommit
add_library(aws-cpp-sdk-codecommit SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-codecommit PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-codecommit/include"
)

# Create imported target aws-cpp-sdk-codedeploy
add_library(aws-cpp-sdk-codedeploy SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-codedeploy PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-codedeploy/include"
)

# Create imported target aws-cpp-sdk-codepipeline
add_library(aws-cpp-sdk-codepipeline SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-codepipeline PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-codepipeline/include"
)

# Create imported target aws-cpp-sdk-cognito-identity
add_library(aws-cpp-sdk-cognito-identity SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-cognito-identity PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-cognito-identity/include"
)

# Create imported target aws-cpp-sdk-cognito-sync
add_library(aws-cpp-sdk-cognito-sync SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-cognito-sync PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-cognito-sync/include"
)

# Create imported target aws-cpp-sdk-config
add_library(aws-cpp-sdk-config SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-config PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-config/include"
)

# Create imported target aws-cpp-sdk-datapipeline
add_library(aws-cpp-sdk-datapipeline SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-datapipeline PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-datapipeline/include"
)

# Create imported target aws-cpp-sdk-devicefarm
add_library(aws-cpp-sdk-devicefarm SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-devicefarm PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-devicefarm/include"
)

# Create imported target aws-cpp-sdk-directconnect
add_library(aws-cpp-sdk-directconnect SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-directconnect PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-directconnect/include"
)

# Create imported target aws-cpp-sdk-dms
add_library(aws-cpp-sdk-dms SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-dms PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-dms/include"
)

# Create imported target aws-cpp-sdk-ds
add_library(aws-cpp-sdk-ds SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-ds PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-ds/include"
)

# Create imported target aws-cpp-sdk-dynamodb
add_library(aws-cpp-sdk-dynamodb SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-dynamodb PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-dynamodb/include"
)

# Create imported target aws-cpp-sdk-ec2
add_library(aws-cpp-sdk-ec2 SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-ec2 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-ec2/include"
)

# Create imported target aws-cpp-sdk-ecs
add_library(aws-cpp-sdk-ecs SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-ecs PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-ecs/include"
)

# Create imported target aws-cpp-sdk-ecr
add_library(aws-cpp-sdk-ecr SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-ecr PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-ecr/include"
)

# Create imported target aws-cpp-sdk-elasticache
add_library(aws-cpp-sdk-elasticache SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-elasticache PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-elasticache/include"
)

# Create imported target aws-cpp-sdk-elasticbeanstalk
add_library(aws-cpp-sdk-elasticbeanstalk SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-elasticbeanstalk PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-elasticbeanstalk/include"
)

# Create imported target aws-cpp-sdk-elasticfilesystem
add_library(aws-cpp-sdk-elasticfilesystem SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-elasticfilesystem PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-elasticfilesystem/include"
)

# Create imported target aws-cpp-sdk-elasticloadbalancing
add_library(aws-cpp-sdk-elasticloadbalancing SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-elasticloadbalancing PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-elasticloadbalancing/include"
)

# Create imported target aws-cpp-sdk-elasticmapreduce
add_library(aws-cpp-sdk-elasticmapreduce SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-elasticmapreduce PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-elasticmapreduce/include"
)

# Create imported target aws-cpp-sdk-elastictranscoder
add_library(aws-cpp-sdk-elastictranscoder SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-elastictranscoder PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-elastictranscoder/include"
)

# Create imported target aws-cpp-sdk-email
add_library(aws-cpp-sdk-email SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-email PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-email/include"
)

# Create imported target aws-cpp-sdk-es
add_library(aws-cpp-sdk-es SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-es PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-es/include"
)

# Create imported target aws-cpp-sdk-events
add_library(aws-cpp-sdk-events SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-events PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-events/include"
)

# Create imported target aws-cpp-sdk-firehose
add_library(aws-cpp-sdk-firehose SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-firehose PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-firehose/include"
)

# Create imported target aws-cpp-sdk-gamelift
add_library(aws-cpp-sdk-gamelift SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-gamelift PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-gamelift/include"
)

# Create imported target aws-cpp-sdk-glacier
add_library(aws-cpp-sdk-glacier SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-glacier PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-glacier/include"
)

# Create imported target aws-cpp-sdk-iam
add_library(aws-cpp-sdk-iam SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-iam PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-iam/include"
)

# Create imported target aws-cpp-sdk-importexport
add_library(aws-cpp-sdk-importexport SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-importexport PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-importexport/include"
)

# Create imported target aws-cpp-sdk-inspector
add_library(aws-cpp-sdk-inspector SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-inspector PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-inspector/include"
)

# Create imported target aws-cpp-sdk-iot
add_library(aws-cpp-sdk-iot SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-iot PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-iot/include"
)

# Create imported target aws-cpp-sdk-identity-management
add_library(aws-cpp-sdk-identity-management SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-identity-management PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-identity-management/include"
)

# Create imported target aws-cpp-sdk-kinesis
add_library(aws-cpp-sdk-kinesis SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-kinesis PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-kinesis/include"
)

# Create imported target aws-cpp-sdk-kms
add_library(aws-cpp-sdk-kms SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-kms PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-kms/include"
)

# Create imported target aws-cpp-sdk-lambda
add_library(aws-cpp-sdk-lambda SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-lambda PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-lambda/include"
)

# Create imported target aws-cpp-sdk-logs
add_library(aws-cpp-sdk-logs SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-logs PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-logs/include"
)

# Create imported target aws-cpp-sdk-machinelearning
add_library(aws-cpp-sdk-machinelearning SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-machinelearning PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-machinelearning/include"
)

# Create imported target aws-cpp-sdk-marketplacecommerceanalytics
add_library(aws-cpp-sdk-marketplacecommerceanalytics SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-marketplacecommerceanalytics PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-marketplacecommerceanalytics/include"
)

# Create imported target aws-cpp-sdk-mobileanalytics
add_library(aws-cpp-sdk-mobileanalytics SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-mobileanalytics PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-mobileanalytics/include"
)

# Create imported target aws-cpp-sdk-meteringmarketplace
add_library(aws-cpp-sdk-meteringmarketplace SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-meteringmarketplace PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-meteringmarketplace/include"
)

# Create imported target aws-cpp-sdk-monitoring
add_library(aws-cpp-sdk-monitoring SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-monitoring PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-monitoring/include"
)

# Create imported target aws-cpp-sdk-opsworks
add_library(aws-cpp-sdk-opsworks SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-opsworks PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-opsworks/include"
)

# Create imported target aws-cpp-sdk-queues
add_library(aws-cpp-sdk-queues SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-queues PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-queues/include"
)

# Create imported target aws-cpp-sdk-rds
add_library(aws-cpp-sdk-rds SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-rds PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-rds/include"
)

# Create imported target aws-cpp-sdk-redshift
add_library(aws-cpp-sdk-redshift SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-redshift PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-redshift/include"
)

# Create imported target aws-cpp-sdk-route53
add_library(aws-cpp-sdk-route53 SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-route53 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-route53/include"
)

# Create imported target aws-cpp-sdk-route53domains
add_library(aws-cpp-sdk-route53domains SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-route53domains PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-route53domains/include"
)

# Create imported target aws-cpp-sdk-s3
add_library(aws-cpp-sdk-s3 SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-s3 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-s3/include"
)

# Create imported target aws-cpp-sdk-sdb
add_library(aws-cpp-sdk-sdb SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-sdb PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-sdb/include"
)

# Create imported target aws-cpp-sdk-sns
add_library(aws-cpp-sdk-sns SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-sns PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-sns/include"
)

# Create imported target aws-cpp-sdk-sqs
add_library(aws-cpp-sdk-sqs SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-sqs PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-sqs/include"
)

# Create imported target aws-cpp-sdk-ssm
add_library(aws-cpp-sdk-ssm SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-ssm PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-ssm/include"
)

# Create imported target aws-cpp-sdk-storagegateway
add_library(aws-cpp-sdk-storagegateway SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-storagegateway PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-storagegateway/include"
)

# Create imported target aws-cpp-sdk-sts
add_library(aws-cpp-sdk-sts SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-sts PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-sts/include"
)

# Create imported target aws-cpp-sdk-support
add_library(aws-cpp-sdk-support SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-support PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-support/include"
)

# Create imported target aws-cpp-sdk-swf
add_library(aws-cpp-sdk-swf SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-swf PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-swf/include"
)

# Create imported target aws-cpp-sdk-transfer
add_library(aws-cpp-sdk-transfer SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-transfer PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-transfer/include"
)

# Create imported target aws-cpp-sdk-waf
add_library(aws-cpp-sdk-waf SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-waf PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-waf/include"
)

# Create imported target aws-cpp-sdk-workspaces
add_library(aws-cpp-sdk-workspaces SHARED IMPORTED)

set_target_properties(aws-cpp-sdk-workspaces PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/srrajeev/Documents/workspace/aws-sdk-cpp/aws-cpp-sdk-workspaces/include"
)

# Import target "aws-cpp-sdk-core" for configuration "Release"
set_property(TARGET aws-cpp-sdk-core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-core PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "pthread;curl"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-core/libaws-cpp-sdk-core.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-core/libaws-cpp-sdk-core.dylib"
  )

# Import target "aws-cpp-sdk-access-management" for configuration "Release"
set_property(TARGET aws-cpp-sdk-access-management APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-access-management PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-cognito-identity;aws-cpp-sdk-iam"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-access-management/libaws-cpp-sdk-access-management.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-access-management/libaws-cpp-sdk-access-management.dylib"
  )

# Import target "aws-cpp-sdk-autoscaling" for configuration "Release"
set_property(TARGET aws-cpp-sdk-autoscaling APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-autoscaling PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-autoscaling/libaws-cpp-sdk-autoscaling.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-autoscaling/libaws-cpp-sdk-autoscaling.dylib"
  )

# Import target "aws-cpp-sdk-acm" for configuration "Release"
set_property(TARGET aws-cpp-sdk-acm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-acm PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-acm/libaws-cpp-sdk-acm.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-acm/libaws-cpp-sdk-acm.dylib"
  )

# Import target "aws-cpp-sdk-apigateway" for configuration "Release"
set_property(TARGET aws-cpp-sdk-apigateway APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-apigateway PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-apigateway/libaws-cpp-sdk-apigateway.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-apigateway/libaws-cpp-sdk-apigateway.dylib"
  )

# Import target "aws-cpp-sdk-cloudhsm" for configuration "Release"
set_property(TARGET aws-cpp-sdk-cloudhsm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-cloudhsm PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cloudhsm/libaws-cpp-sdk-cloudhsm.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cloudhsm/libaws-cpp-sdk-cloudhsm.dylib"
  )

# Import target "aws-cpp-sdk-cloudformation" for configuration "Release"
set_property(TARGET aws-cpp-sdk-cloudformation APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-cloudformation PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cloudformation/libaws-cpp-sdk-cloudformation.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cloudformation/libaws-cpp-sdk-cloudformation.dylib"
  )

# Import target "aws-cpp-sdk-cloudfront" for configuration "Release"
set_property(TARGET aws-cpp-sdk-cloudfront APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-cloudfront PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cloudfront/libaws-cpp-sdk-cloudfront.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cloudfront/libaws-cpp-sdk-cloudfront.dylib"
  )

# Import target "aws-cpp-sdk-cloudsearch" for configuration "Release"
set_property(TARGET aws-cpp-sdk-cloudsearch APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-cloudsearch PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cloudsearch/libaws-cpp-sdk-cloudsearch.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cloudsearch/libaws-cpp-sdk-cloudsearch.dylib"
  )

# Import target "aws-cpp-sdk-cloudsearchdomain" for configuration "Release"
set_property(TARGET aws-cpp-sdk-cloudsearchdomain APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-cloudsearchdomain PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cloudsearchdomain/libaws-cpp-sdk-cloudsearchdomain.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cloudsearchdomain/libaws-cpp-sdk-cloudsearchdomain.dylib"
  )

# Import target "aws-cpp-sdk-cloudtrail" for configuration "Release"
set_property(TARGET aws-cpp-sdk-cloudtrail APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-cloudtrail PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cloudtrail/libaws-cpp-sdk-cloudtrail.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cloudtrail/libaws-cpp-sdk-cloudtrail.dylib"
  )

# Import target "aws-cpp-sdk-codecommit" for configuration "Release"
set_property(TARGET aws-cpp-sdk-codecommit APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-codecommit PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-codecommit/libaws-cpp-sdk-codecommit.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-codecommit/libaws-cpp-sdk-codecommit.dylib"
  )

# Import target "aws-cpp-sdk-codedeploy" for configuration "Release"
set_property(TARGET aws-cpp-sdk-codedeploy APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-codedeploy PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-codedeploy/libaws-cpp-sdk-codedeploy.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-codedeploy/libaws-cpp-sdk-codedeploy.dylib"
  )

# Import target "aws-cpp-sdk-codepipeline" for configuration "Release"
set_property(TARGET aws-cpp-sdk-codepipeline APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-codepipeline PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-codepipeline/libaws-cpp-sdk-codepipeline.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-codepipeline/libaws-cpp-sdk-codepipeline.dylib"
  )

# Import target "aws-cpp-sdk-cognito-identity" for configuration "Release"
set_property(TARGET aws-cpp-sdk-cognito-identity APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-cognito-identity PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cognito-identity/libaws-cpp-sdk-cognito-identity.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cognito-identity/libaws-cpp-sdk-cognito-identity.dylib"
  )

# Import target "aws-cpp-sdk-cognito-sync" for configuration "Release"
set_property(TARGET aws-cpp-sdk-cognito-sync APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-cognito-sync PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cognito-sync/libaws-cpp-sdk-cognito-sync.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cognito-sync/libaws-cpp-sdk-cognito-sync.dylib"
  )

# Import target "aws-cpp-sdk-config" for configuration "Release"
set_property(TARGET aws-cpp-sdk-config APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-config PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-config/libaws-cpp-sdk-config.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-config/libaws-cpp-sdk-config.dylib"
  )

# Import target "aws-cpp-sdk-datapipeline" for configuration "Release"
set_property(TARGET aws-cpp-sdk-datapipeline APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-datapipeline PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-datapipeline/libaws-cpp-sdk-datapipeline.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-datapipeline/libaws-cpp-sdk-datapipeline.dylib"
  )

# Import target "aws-cpp-sdk-devicefarm" for configuration "Release"
set_property(TARGET aws-cpp-sdk-devicefarm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-devicefarm PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-devicefarm/libaws-cpp-sdk-devicefarm.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-devicefarm/libaws-cpp-sdk-devicefarm.dylib"
  )

# Import target "aws-cpp-sdk-directconnect" for configuration "Release"
set_property(TARGET aws-cpp-sdk-directconnect APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-directconnect PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-directconnect/libaws-cpp-sdk-directconnect.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-directconnect/libaws-cpp-sdk-directconnect.dylib"
  )

# Import target "aws-cpp-sdk-dms" for configuration "Release"
set_property(TARGET aws-cpp-sdk-dms APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-dms PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-dms/libaws-cpp-sdk-dms.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-dms/libaws-cpp-sdk-dms.dylib"
  )

# Import target "aws-cpp-sdk-ds" for configuration "Release"
set_property(TARGET aws-cpp-sdk-ds APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-ds PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-ds/libaws-cpp-sdk-ds.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-ds/libaws-cpp-sdk-ds.dylib"
  )

# Import target "aws-cpp-sdk-dynamodb" for configuration "Release"
set_property(TARGET aws-cpp-sdk-dynamodb APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-dynamodb PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-dynamodb/libaws-cpp-sdk-dynamodb.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-dynamodb/libaws-cpp-sdk-dynamodb.dylib"
  )

# Import target "aws-cpp-sdk-ec2" for configuration "Release"
set_property(TARGET aws-cpp-sdk-ec2 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-ec2 PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-ec2/libaws-cpp-sdk-ec2.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-ec2/libaws-cpp-sdk-ec2.dylib"
  )

# Import target "aws-cpp-sdk-ecs" for configuration "Release"
set_property(TARGET aws-cpp-sdk-ecs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-ecs PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-ecs/libaws-cpp-sdk-ecs.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-ecs/libaws-cpp-sdk-ecs.dylib"
  )

# Import target "aws-cpp-sdk-ecr" for configuration "Release"
set_property(TARGET aws-cpp-sdk-ecr APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-ecr PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-ecr/libaws-cpp-sdk-ecr.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-ecr/libaws-cpp-sdk-ecr.dylib"
  )

# Import target "aws-cpp-sdk-elasticache" for configuration "Release"
set_property(TARGET aws-cpp-sdk-elasticache APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-elasticache PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-elasticache/libaws-cpp-sdk-elasticache.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-elasticache/libaws-cpp-sdk-elasticache.dylib"
  )

# Import target "aws-cpp-sdk-elasticbeanstalk" for configuration "Release"
set_property(TARGET aws-cpp-sdk-elasticbeanstalk APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-elasticbeanstalk PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-elasticbeanstalk/libaws-cpp-sdk-elasticbeanstalk.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-elasticbeanstalk/libaws-cpp-sdk-elasticbeanstalk.dylib"
  )

# Import target "aws-cpp-sdk-elasticfilesystem" for configuration "Release"
set_property(TARGET aws-cpp-sdk-elasticfilesystem APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-elasticfilesystem PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-elasticfilesystem/libaws-cpp-sdk-elasticfilesystem.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-elasticfilesystem/libaws-cpp-sdk-elasticfilesystem.dylib"
  )

# Import target "aws-cpp-sdk-elasticloadbalancing" for configuration "Release"
set_property(TARGET aws-cpp-sdk-elasticloadbalancing APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-elasticloadbalancing PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-elasticloadbalancing/libaws-cpp-sdk-elasticloadbalancing.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-elasticloadbalancing/libaws-cpp-sdk-elasticloadbalancing.dylib"
  )

# Import target "aws-cpp-sdk-elasticmapreduce" for configuration "Release"
set_property(TARGET aws-cpp-sdk-elasticmapreduce APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-elasticmapreduce PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-elasticmapreduce/libaws-cpp-sdk-elasticmapreduce.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-elasticmapreduce/libaws-cpp-sdk-elasticmapreduce.dylib"
  )

# Import target "aws-cpp-sdk-elastictranscoder" for configuration "Release"
set_property(TARGET aws-cpp-sdk-elastictranscoder APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-elastictranscoder PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-elastictranscoder/libaws-cpp-sdk-elastictranscoder.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-elastictranscoder/libaws-cpp-sdk-elastictranscoder.dylib"
  )

# Import target "aws-cpp-sdk-email" for configuration "Release"
set_property(TARGET aws-cpp-sdk-email APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-email PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-email/libaws-cpp-sdk-email.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-email/libaws-cpp-sdk-email.dylib"
  )

# Import target "aws-cpp-sdk-es" for configuration "Release"
set_property(TARGET aws-cpp-sdk-es APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-es PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-es/libaws-cpp-sdk-es.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-es/libaws-cpp-sdk-es.dylib"
  )

# Import target "aws-cpp-sdk-events" for configuration "Release"
set_property(TARGET aws-cpp-sdk-events APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-events PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-events/libaws-cpp-sdk-events.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-events/libaws-cpp-sdk-events.dylib"
  )

# Import target "aws-cpp-sdk-firehose" for configuration "Release"
set_property(TARGET aws-cpp-sdk-firehose APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-firehose PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-firehose/libaws-cpp-sdk-firehose.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-firehose/libaws-cpp-sdk-firehose.dylib"
  )

# Import target "aws-cpp-sdk-gamelift" for configuration "Release"
set_property(TARGET aws-cpp-sdk-gamelift APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-gamelift PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-gamelift/libaws-cpp-sdk-gamelift.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-gamelift/libaws-cpp-sdk-gamelift.dylib"
  )

# Import target "aws-cpp-sdk-glacier" for configuration "Release"
set_property(TARGET aws-cpp-sdk-glacier APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-glacier PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-glacier/libaws-cpp-sdk-glacier.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-glacier/libaws-cpp-sdk-glacier.dylib"
  )

# Import target "aws-cpp-sdk-iam" for configuration "Release"
set_property(TARGET aws-cpp-sdk-iam APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-iam PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-iam/libaws-cpp-sdk-iam.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-iam/libaws-cpp-sdk-iam.dylib"
  )

# Import target "aws-cpp-sdk-importexport" for configuration "Release"
set_property(TARGET aws-cpp-sdk-importexport APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-importexport PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-importexport/libaws-cpp-sdk-importexport.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-importexport/libaws-cpp-sdk-importexport.dylib"
  )

# Import target "aws-cpp-sdk-inspector" for configuration "Release"
set_property(TARGET aws-cpp-sdk-inspector APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-inspector PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-inspector/libaws-cpp-sdk-inspector.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-inspector/libaws-cpp-sdk-inspector.dylib"
  )

# Import target "aws-cpp-sdk-iot" for configuration "Release"
set_property(TARGET aws-cpp-sdk-iot APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-iot PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-iot/libaws-cpp-sdk-iot.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-iot/libaws-cpp-sdk-iot.dylib"
  )

# Import target "aws-cpp-sdk-identity-management" for configuration "Release"
set_property(TARGET aws-cpp-sdk-identity-management APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-identity-management PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-cognito-identity"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-identity-management/libaws-cpp-sdk-identity-management.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-identity-management/libaws-cpp-sdk-identity-management.dylib"
  )

# Import target "aws-cpp-sdk-kinesis" for configuration "Release"
set_property(TARGET aws-cpp-sdk-kinesis APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-kinesis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-kinesis/libaws-cpp-sdk-kinesis.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-kinesis/libaws-cpp-sdk-kinesis.dylib"
  )

# Import target "aws-cpp-sdk-kms" for configuration "Release"
set_property(TARGET aws-cpp-sdk-kms APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-kms PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-kms/libaws-cpp-sdk-kms.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-kms/libaws-cpp-sdk-kms.dylib"
  )

# Import target "aws-cpp-sdk-lambda" for configuration "Release"
set_property(TARGET aws-cpp-sdk-lambda APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-lambda PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-lambda/libaws-cpp-sdk-lambda.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-lambda/libaws-cpp-sdk-lambda.dylib"
  )

# Import target "aws-cpp-sdk-logs" for configuration "Release"
set_property(TARGET aws-cpp-sdk-logs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-logs PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-logs/libaws-cpp-sdk-logs.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-logs/libaws-cpp-sdk-logs.dylib"
  )

# Import target "aws-cpp-sdk-machinelearning" for configuration "Release"
set_property(TARGET aws-cpp-sdk-machinelearning APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-machinelearning PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-machinelearning/libaws-cpp-sdk-machinelearning.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-machinelearning/libaws-cpp-sdk-machinelearning.dylib"
  )

# Import target "aws-cpp-sdk-marketplacecommerceanalytics" for configuration "Release"
set_property(TARGET aws-cpp-sdk-marketplacecommerceanalytics APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-marketplacecommerceanalytics PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-marketplacecommerceanalytics/libaws-cpp-sdk-marketplacecommerceanalytics.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-marketplacecommerceanalytics/libaws-cpp-sdk-marketplacecommerceanalytics.dylib"
  )

# Import target "aws-cpp-sdk-mobileanalytics" for configuration "Release"
set_property(TARGET aws-cpp-sdk-mobileanalytics APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-mobileanalytics PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-mobileanalytics/libaws-cpp-sdk-mobileanalytics.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-mobileanalytics/libaws-cpp-sdk-mobileanalytics.dylib"
  )

# Import target "aws-cpp-sdk-meteringmarketplace" for configuration "Release"
set_property(TARGET aws-cpp-sdk-meteringmarketplace APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-meteringmarketplace PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-meteringmarketplace/libaws-cpp-sdk-meteringmarketplace.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-meteringmarketplace/libaws-cpp-sdk-meteringmarketplace.dylib"
  )

# Import target "aws-cpp-sdk-monitoring" for configuration "Release"
set_property(TARGET aws-cpp-sdk-monitoring APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-monitoring PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-monitoring/libaws-cpp-sdk-monitoring.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-monitoring/libaws-cpp-sdk-monitoring.dylib"
  )

# Import target "aws-cpp-sdk-opsworks" for configuration "Release"
set_property(TARGET aws-cpp-sdk-opsworks APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-opsworks PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-opsworks/libaws-cpp-sdk-opsworks.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-opsworks/libaws-cpp-sdk-opsworks.dylib"
  )

# Import target "aws-cpp-sdk-queues" for configuration "Release"
set_property(TARGET aws-cpp-sdk-queues APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-queues PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-sqs"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-queues/libaws-cpp-sdk-queues.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-queues/libaws-cpp-sdk-queues.dylib"
  )

# Import target "aws-cpp-sdk-rds" for configuration "Release"
set_property(TARGET aws-cpp-sdk-rds APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-rds PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-rds/libaws-cpp-sdk-rds.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-rds/libaws-cpp-sdk-rds.dylib"
  )

# Import target "aws-cpp-sdk-redshift" for configuration "Release"
set_property(TARGET aws-cpp-sdk-redshift APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-redshift PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-redshift/libaws-cpp-sdk-redshift.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-redshift/libaws-cpp-sdk-redshift.dylib"
  )

# Import target "aws-cpp-sdk-route53" for configuration "Release"
set_property(TARGET aws-cpp-sdk-route53 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-route53 PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-route53/libaws-cpp-sdk-route53.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-route53/libaws-cpp-sdk-route53.dylib"
  )

# Import target "aws-cpp-sdk-route53domains" for configuration "Release"
set_property(TARGET aws-cpp-sdk-route53domains APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-route53domains PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-route53domains/libaws-cpp-sdk-route53domains.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-route53domains/libaws-cpp-sdk-route53domains.dylib"
  )

# Import target "aws-cpp-sdk-s3" for configuration "Release"
set_property(TARGET aws-cpp-sdk-s3 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-s3 PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-s3/libaws-cpp-sdk-s3.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-s3/libaws-cpp-sdk-s3.dylib"
  )

# Import target "aws-cpp-sdk-sdb" for configuration "Release"
set_property(TARGET aws-cpp-sdk-sdb APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-sdb PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-sdb/libaws-cpp-sdk-sdb.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-sdb/libaws-cpp-sdk-sdb.dylib"
  )

# Import target "aws-cpp-sdk-sns" for configuration "Release"
set_property(TARGET aws-cpp-sdk-sns APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-sns PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-sns/libaws-cpp-sdk-sns.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-sns/libaws-cpp-sdk-sns.dylib"
  )

# Import target "aws-cpp-sdk-sqs" for configuration "Release"
set_property(TARGET aws-cpp-sdk-sqs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-sqs PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-sqs/libaws-cpp-sdk-sqs.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-sqs/libaws-cpp-sdk-sqs.dylib"
  )

# Import target "aws-cpp-sdk-ssm" for configuration "Release"
set_property(TARGET aws-cpp-sdk-ssm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-ssm PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-ssm/libaws-cpp-sdk-ssm.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-ssm/libaws-cpp-sdk-ssm.dylib"
  )

# Import target "aws-cpp-sdk-storagegateway" for configuration "Release"
set_property(TARGET aws-cpp-sdk-storagegateway APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-storagegateway PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-storagegateway/libaws-cpp-sdk-storagegateway.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-storagegateway/libaws-cpp-sdk-storagegateway.dylib"
  )

# Import target "aws-cpp-sdk-sts" for configuration "Release"
set_property(TARGET aws-cpp-sdk-sts APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-sts PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-sts/libaws-cpp-sdk-sts.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-sts/libaws-cpp-sdk-sts.dylib"
  )

# Import target "aws-cpp-sdk-support" for configuration "Release"
set_property(TARGET aws-cpp-sdk-support APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-support PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-support/libaws-cpp-sdk-support.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-support/libaws-cpp-sdk-support.dylib"
  )

# Import target "aws-cpp-sdk-swf" for configuration "Release"
set_property(TARGET aws-cpp-sdk-swf APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-swf PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-swf/libaws-cpp-sdk-swf.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-swf/libaws-cpp-sdk-swf.dylib"
  )

# Import target "aws-cpp-sdk-transfer" for configuration "Release"
set_property(TARGET aws-cpp-sdk-transfer APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-transfer PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-s3"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-transfer/libaws-cpp-sdk-transfer.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-transfer/libaws-cpp-sdk-transfer.dylib"
  )

# Import target "aws-cpp-sdk-waf" for configuration "Release"
set_property(TARGET aws-cpp-sdk-waf APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-waf PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-waf/libaws-cpp-sdk-waf.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-waf/libaws-cpp-sdk-waf.dylib"
  )

# Import target "aws-cpp-sdk-workspaces" for configuration "Release"
set_property(TARGET aws-cpp-sdk-workspaces APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aws-cpp-sdk-workspaces PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "aws-cpp-sdk-core"
  IMPORTED_LOCATION_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-workspaces/libaws-cpp-sdk-workspaces.dylib"
  IMPORTED_SONAME_RELEASE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-workspaces/libaws-cpp-sdk-workspaces.dylib"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
