# Install script for directory: /Users/srrajeev/Documents/workspace/aws-sdk-cpp

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-core/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/testing-resources/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-access-management/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-autoscaling/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-acm/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-apigateway/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cloudhsm/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cloudformation/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cloudfront/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cloudsearch/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cloudsearchdomain/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cloudtrail/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-codecommit/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-codedeploy/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-codepipeline/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cognito-identity/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cognito-sync/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-config/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-datapipeline/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-devicefarm/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-directconnect/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-dms/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-ds/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-dynamodb/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-ec2/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-ecs/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-ecr/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-elasticache/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-elasticbeanstalk/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-elasticfilesystem/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-elasticloadbalancing/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-elasticmapreduce/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-elastictranscoder/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-email/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-es/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-events/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-firehose/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-gamelift/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-glacier/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-iam/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-importexport/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-inspector/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-iot/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-identity-management/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-kinesis/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-kms/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-lambda/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-logs/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-machinelearning/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-marketplacecommerceanalytics/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-mobileanalytics/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-meteringmarketplace/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-monitoring/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-opsworks/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-queues/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-rds/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-redshift/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-route53/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-route53domains/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-s3/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-sdb/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-sns/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-sqs/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-ssm/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-storagegateway/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-sts/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-support/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-swf/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-transfer/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-waf/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-workspaces/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-core-tests/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-dynamodb-integration-tests/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-cognitoidentity-integration-tests/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-sqs-integration-tests/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-lambda-integration-tests/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-s3-integration-tests/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-identity-management-tests/cmake_install.cmake")
  include("/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/aws-cpp-sdk-transfer-tests/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "/Users/srrajeev/Documents/workspace/aws-sdk-cpp-build/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
